services:
  postgres-dev:
    container_name: "postgres-dev"
    pull_policy: always
    # https://github.com/baosystems/docker-postgis/pkgs/container/postgis
    image: ghcr.io/baosystems/postgis:18
    command: postgres -c 'max_connections=1000'
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?Copy env.example to .env and set POSTGRES_PASSWORD}
    volumes:
      - postgres-dev-data:/var/lib/postgresql
    ports:
      - "127.0.0.1:5432:5432"

volumes:
  postgres-dev-data:
